### ISSUE TITLE
Obtener la máquina AWS EC2 para el ambiente de desarrollo [1]

### ISSUE THREAD

**Issue by Eddy-Palo** [e2innovation/rul-wrs#7]
Get the AWS EC2 machine for the development environment.

**Comment by Eddy-Palo** [comment]
The virtual machine was created
Public DNS: ec2-54-218-34-89.us-west-2.compute.amazonaws.com
user: Administrator
pwd: %NWfGpTBRXf
please let me know to turn on the machine because it has a cost
please review and confirm @juanuy1985 @BriggiRivera @eluqm

**Comment by BriggiRivera** [comment]
@Eddy-Palo  según lo conversado, por favor, hay que crear una nueva máquina que sea gratuita.
